# kubectl create clusterrolebinding default-view --clusterrole=view --serviceaccount=default:defaulta
# apply above line first
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientgoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientgoapp
  template:
    metadata:
      name: clientgoapp
      labels:
        app: clientgoapp
    spec:
      containers:
      - name: app
        image: docker.io/muthurajrprivaterepo/sampleclientgo:v3.3
        command:
        - /app
        #set interval flag (default 60s)
        - interval=60
        ports:
        - name: http-metrics
          containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: mutate-metrics
  labels:
    app: clientgoapp
spec:
  selector: 
    app: clientgoapp
  ports:
    - port: 8888
      targetPort: 8888
      name: http-metrics