FROM debian
COPY ./app /app
ENTRYPOINT /app

# export GO111MODULE=on;
# go mod tidy
# GOOS=linux go build -o ./app .
# docker build -t muthurajrprivaterepo/sampleclientgo:v5.4 .
# docker push muthurajrprivaterepo/sampleclientgo:v5.4
# minikube image build -t muthurajrprivaterepo/sampleclientgo:v3.5 .