FROM debian
COPY ./app /app
ENTRYPOINT /app

# GOOS=linux go build -o ./app .
# docker build -t muthurajrprivaterepo/sampleclientgo:v4.0 .
# docker push muthurajrprivaterepo/sampleclientgo:v4.0
# minikube image build -t muthurajrprivaterepo/sampleclientgo:v3.1 .