apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yacecredentials
  namespace: yace
spec:
  encryptedData:
    credentials: AgCWBFkumOFsaAaOFggmM5H0ic4E6GqNhlgHAc46RZJPYDxDXV2gDavRnAAV11cQNxCsNRWEEAI29ANCnEOJUK48kpcgdcTEhBywlMMc+etBKizBJuRS7eW7vJBx1wOMWoRijF91iTh4RPaoYmJhBHMuTN1cSd30LieJhDFZCH/Yz8hk7mp+UARnGZlvZS7vyLLlYd6748PWRmN2JagN2tOOpUpv3/TbIm8q+5Jpf0nNaY7eduk38OUl8wV4jta6diQOXn8vWH5igHomI+8JudAVYQGd/JXaJQrwwF5PsoPkTDP4jEQEUK9OOaLmv6BwU2W2HF+4H0fp1FdcAe2Of+t5xAUV9SmspuOK3pbVxLngOxOmm9PnZ4OIvyXwiAVofStEhZZOV3F+7U53eHWfoYUPsvIY6cLoSFC+4oQyBr0IKbjQhe3Gu6MPkmIDMPuGrMfuqW0QvcSokPX78bUOH+rxMx57tEawPAzTul8jr2EscNjWDspIcN0p3gvtXpiVcPRh+1iN2QoZoa/TL2AvjJAeXQoL7cs2M9gCN92JpNvlipp1V9F/8lgGEyNEOAKSDI+aElJeRL5ABlQc1MDq9HF/F/mZyHw+faCF+JAxgtD4hPaw7ztMgGAVVDKEH9hGYxqii/XKUkgQ5hDYFK7P73Vbl7cumxRM8YieFTTS3vrZRyf9ZP7l7jYB7NIxm5YIsPF81xFowDKwYg8E6h4e+D0V96dtgREnbHJlQsmvIpPbxPWMxLkSiLf+TPFs54I49aiAEUoLeJyIXgHGo8Ogx0mAfr3t96EgpXRap3/L1DnwqTfVrMNNhfNBJagdm57FCLuuV39E8KeO3N8yshhOlk9BmN5Luw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: yacecredentials
      namespace: yace
    type: Opaque

