apiVersion: v1
kind: Secret
metadata:
  name: yacecredentials
type: Opaque
data:
  credentials: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVlTVE1aRkNJUEdRRENSSEoKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gL005c0Z0YmIvY2VsdDlyL24rV2lZVGU5UUoydHBicTkzSk84RnhkaQo=


# https://raw.githubusercontent.com/jonahjon/promcat/master/yace/yace_s3.yaml

# kubeseal --format=yaml < secret.yaml > sealed-secret.yaml