apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: nginx
    image: nginx:latest
### Everything below is added by the webhook ###
