apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pod-identity-webhook
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    path: /metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: pod-identity-webhook
