apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yace
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: yace-metrics
    path: /metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      name: yace
      app: yace
