apiVersion: v1
kind: ConfigMap
metadata:
  name: yace
data:
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        elb: 
          - env
      jobs:
      - regions: 
          - us-east-1
        type: elb
        searchTags:
          - key: name
            value: yace-elb
        enableMetricData: true
        metrics:
          - name: HealthyHostCount
            statistics:
            - Average
            period: 300
            length: 600
          - name: BackendConnectionErrors
            statistics:
            - Average
            period: 300
            length: 600
          - name: EstimatedALBConsumedLCUs
            statistics:
            - Average
            period: 300
            length: 600
---




