apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
spec:
  endpoints:
  - interval: 30s
    port: http-monitoring
    #targetPort: "15014"
    scheme: http
  jobLabel: app
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: istiod
